a) Filter as of Currrent Date - System Date with 1st Date of Month - Last Date of Month
    #"Date Filtered" = Table.SelectRows(#"Changed Type1", each [Date of Separation] >= Date.StartOfMonth(Date.AddMonths(Date.From(DateTime.LocalNow()),-1)) and [Date of Separation] <= Date.EndOfMonth(Date.From(DateTime.LocalNow())))


b) Filtered as of Current Month - Date Local Time

// DateTime.LocalNow()

    #"Added on Month of Birth" = Table.AddColumn(#"Age Filtered", "Month Name", each Date.Month([Birth date]), Int8.Type),
    #"Filtered Rows" = Table.SelectRows(#"Added on Month of Birth", each ([Month Name] = Date.Month(DateTime.LocalNow())))


OR

// If Statement

    #"Custom Filtered on Current Month" = Table.AddColumn(#"Added on Month of Birth", "Current Month Indicator", each if Date.Month(DateTime.LocalNow())=[Month Name] then "Current Month" else "Not Current Month"),
    #"CurrentMonth Selected - filtered" = Table.SelectRows(#"Custom Filtered on Current Month", each ([Current Month Indicator] = "Current Month")),

c) PowerBI M Query Date Function - Filter Quater Months and LastMonth Data

  #"Filtered Rows" = Table.SelectRows(#"Changed Type1", each Date.Month([Reporting Period]) = 3 or Date.Month([Reporting Period]) = 6 or Date.Month([Reporting Period]) = 9 or Date.Month([Reporting Period]) = 12 or Date.IsInPreviousNMonths([Reporting Period],1))

// Explanation:-
1. Date.Month will need to be added under Date datatype which it will automatically captured the Month from the date data
2. Date.IsInPreviousNMonths([Column Name],n)) - the no. in the back = previous n months. You can do this using the Date.IsInPreviousNMonths function on your [Date] column.
Here, n is the number of months you want to check. With Local.DateTime formula = 
Date.IsInPreviousNMonths( Date.AddMonths( DateTime.FixedLocalNow(), -2 ), 3 )


Further reference: https://powerquery.how/date-isinpreviousnmonths/
